/**
 * Wichtigste und größte ICE Haltestellen in Deutschland
 * Geprioritisiert nach Größe und Bedeutung
 */
export interface ICEStation {
  name: string
  displayName: string
  region: string
  lat: number
  lon: number
  isDefault: boolean // Pre-selected by default
}

export const ICE_STATIONS: ICEStation[] = [
  // Tier 1: Größte Städte - VORGEWÄHLT
  {
    name: "BERLIN",
    displayName: "Berlin",
    region: "Berlin",
    lat: 52.525592,
    lon: 13.369715,
    isDefault: true,
  },
  {
    name: "MÜNCHEN",
    displayName: "München",
    region: "Bayern",
    lat: 48.14089,
    lon: 11.558341,
    isDefault: true,
  },
  {
    name: "KÖLN",
    displayName: "Köln",
    region: "Nordrhein-Westfalen",
    lat: 50.943173,
    lon: 6.958665,
    isDefault: true,
  },
  {
    name: "FRANKFURT(MAIN)",
    displayName: "Frankfurt (Main)",
    region: "Hessen",
    lat: 50.106778,
    lon: 8.663385,
    isDefault: true,
  },
  {
    name: "HAMBURG",
    displayName: "Hamburg",
    region: "Hamburg",
    lat: 53.552586,
    lon: 10.006696,
    isDefault: true,
  },
  {
    name: "Stuttgart Hbf",
    displayName: "Stuttgart Hauptbahnhof",
    region: "Baden-Württemberg",
    lat: 48.784158,
    lon: 9.181332,
    isDefault: true,
  },
  {
    name: "Hannover Hbf",
    displayName: "Hannover Hauptbahnhof",
    region: "Niedersachsen",
    lat: 52.376389,
    lon: 9.741944,
    isDefault: true,
  },
  {
    name: "Leipzig Hbf",
    displayName: "Leipzig Hauptbahnhof",
    region: "Sachsen",
    lat: 51.34508,
    lon: 12.381167,
    isDefault: true,
  },
  {
    name: "Dresden Hbf",
    displayName: "Dresden Hauptbahnhof",
    region: "Sachsen",
    lat: 51.0406,
    lon: 13.7326,
    isDefault: true,
  },
  {
    name: "Düsseldorf Hbf",
    displayName: "Düsseldorf Hauptbahnhof",
    region: "Nordrhein-Westfalen",
    lat: 51.219707,
    lon: 6.794011,
    isDefault: true,
  },

  // Tier 2: Wichtige Städte - NICHT vorgewählt
  {
    name: "NÜRNBERG",
    displayName: "Nürnberg",
    region: "Bayern",
    lat: 49.445435,
    lon: 11.08227,
    isDefault: false,
  },
  {
    name: "Essen Hbf",
    displayName: "Essen Hauptbahnhof",
    region: "Nordrhein-Westfalen",
    lat: 51.455,
    lon: 7.015,
    isDefault: false,
  },
  {
    name: "BONN",
    displayName: "Bonn",
    region: "Nordrhein-Westfalen",
    lat: 50.732894,
    lon: 7.099833,
    isDefault: false,
  },
  {
    name: "Basel SBB",
    displayName: "Basel Badischer Bahnhof",
    region: "Baden-Württemberg",
    lat: 47.5476,
    lon: 7.5899,
    isDefault: false,
  },
  {
    name: "Mannheim Hbf",
    displayName: "Mannheim Hauptbahnhof",
    region: "Baden-Württemberg",
    lat: 49.47918,
    lon: 8.469268,
    isDefault: false,
  },
  {
    name: "Karlsruhe Hbf",
    displayName: "Karlsruhe Hauptbahnhof",
    region: "Baden-Württemberg",
    lat: 48.99353,
    lon: 8.401939,
    isDefault: false,
  },
  {
    name: "Wiesbaden Hbf",
    displayName: "Wiesbaden Hauptbahnhof",
    region: "Hessen",
    lat: 50.0704,
    lon: 8.2502,
    isDefault: false,
  },
  {
    name: "Darmstadt Hbf",
    displayName: "Darmstadt Hauptbahnhof",
    region: "Hessen",
    lat: 49.8753,
    lon: 8.6332,
    isDefault: false,
  },
  {
    name: "Augsburg Hbf",
    displayName: "Augsburg Hauptbahnhof",
    region: "Bayern",
    lat: 48.363,
    lon: 10.8919,
    isDefault: false,
  },
  {
    name: "Regensburg Hbf",
    displayName: "Regensburg Hauptbahnhof",
    region: "Bayern",
    lat: 49.01175,
    lon: 12.099669,
    isDefault: false,
  },
  {
    name: "Passau Hbf",
    displayName: "Passau Hauptbahnhof",
    region: "Bayern",
    lat: 48.5758,
    lon: 13.4564,
    isDefault: false,
  },
  {
    name: "Koblenz Hbf",
    displayName: "Koblenz Hauptbahnhof",
    region: "Rheinland-Pfalz",
    lat: 50.3535,
    lon: 7.5993,
    isDefault: false,
  },
  {
    name: "Mainz Hbf",
    displayName: "Mainz Hauptbahnhof",
    region: "Rheinland-Pfalz",
    lat: 50.00124,
    lon: 8.258453,
    isDefault: false,
  },
  {
    name: "Heidelberg Hbf",
    displayName: "Heidelberg Hauptbahnhof",
    region: "Baden-Württemberg",
    lat: 49.403584,
    lon: 8.67548,
    isDefault: false,
  },
  {
    name: "Freiburg Hbf",
    displayName: "Freiburg Hauptbahnhof",
    region: "Baden-Württemberg",
    lat: 47.997974,
    lon: 7.841344,
    isDefault: false,
  },
  {
    name: "Ulm Hbf",
    displayName: "Ulm Hauptbahnhof",
    region: "Baden-Württemberg",
    lat: 48.3956,
    lon: 9.9816,
    isDefault: false,
  },
  {
    name: "Rostock Hbf",
    displayName: "Rostock Hauptbahnhof",
    region: "Mecklenburg-Vorpommern",
    lat: 54.078197,
    lon: 12.131257,
    isDefault: false,
  },
  {
    name: "Greifswald Hbf",
    displayName: "Greifswald Hauptbahnhof",
    region: "Mecklenburg-Vorpommern",
    lat: 54.0923,
    lon: 13.3826,
    isDefault: false,
  },
  {
    name: "Stralsund Hbf",
    displayName: "Stralsund Hauptbahnhof",
    region: "Mecklenburg-Vorpommern",
    lat: 54.308437,
    lon: 13.078028,
    isDefault: false,
  },
  {
    name: "Braunschweig Hbf",
    displayName: "Braunschweig Hauptbahnhof",
    region: "Niedersachsen",
    lat: 52.25213,
    lon: 10.540436,
    isDefault: false,
  },
  {
    name: "Göttingen Hbf",
    displayName: "Göttingen Hauptbahnhof",
    region: "Niedersachsen",
    lat: 51.5353,
    lon: 9.9232,
    isDefault: false,
  },
  {
    name: "Osnabrück Hbf",
    displayName: "Osnabrück Hauptbahnhof",
    region: "Niedersachsen",
    lat: 52.2731,
    lon: 8.0672,
    isDefault: false,
  },
  {
    name: "Bremen Hbf",
    displayName: "Bremen Hauptbahnhof",
    region: "Bremen",
    lat: 53.0834,
    lon: 8.8158,
    isDefault: false,
  },
  {
    name: "Bielefeld Hbf",
    displayName: "Bielefeld Hauptbahnhof",
    region: "Nordrhein-Westfalen",
    lat: 52.0313,
    lon: 8.5348,
    isDefault: false,
  },
  {
    name: "Dortmund Hbf",
    displayName: "Dortmund Hauptbahnhof",
    region: "Nordrhein-Westfalen",
    lat: 51.5178,
    lon: 7.4529,
    isDefault: false,
  },
  {
    name: "Aachen Hbf",
    displayName: "Aachen Hauptbahnhof",
    region: "Nordrhein-Westfalen",
    lat: 50.7665,
    lon: 6.0858,
    isDefault: false,
  },
  {
    name: "Wuppertal Hbf",
    displayName: "Wuppertal Hauptbahnhof",
    region: "Nordrhein-Westfalen",
    lat: 51.2557,
    lon: 7.1605,
    isDefault: false,
  },
  {
    name: "Münster Hbf",
    displayName: "Münster Hauptbahnhof",
    region: "Nordrhein-Westfalen",
    lat: 51.9562,
    lon: 7.6416,
    isDefault: false,
  },
  {
    name: "Kiel Hbf",
    displayName: "Kiel Hauptbahnhof",
    region: "Schleswig-Holstein",
    lat: 54.3131,
    lon: 10.1291,
    isDefault: false,
  },
  {
    name: "JENA",
    displayName: "Jena",
    region: "Thüringen",
    lat: 50.924915,
    lon: 11.587599,
    isDefault: false,
  },
  {
    name: "Erfurt Hbf",
    displayName: "Erfurt Hauptbahnhof",
    region: "Thüringen",
    lat: 50.97255,
    lon: 11.038502,
    isDefault: false,
  },
  {
    name: "Chemnitz Hbf",
    displayName: "Chemnitz Hauptbahnhof",
    region: "Sachsen",
    lat: 50.838333,
    lon: 12.930713,
    isDefault: false,
  },

  // Weitere deutsche Städte
  {
    name: "Lübeck Hbf",
    displayName: "Lübeck Hauptbahnhof",
    region: "Schleswig-Holstein",
    lat: 53.8667,
    lon: 10.6833,
    isDefault: false,
  },
  {
    name: "Flensburg",
    displayName: "Flensburg",
    region: "Schleswig-Holstein",
    lat: 54.7743,
    lon: 9.4367,
    isDefault: false,
  },
  {
    name: "Magdeburg Hbf",
    displayName: "Magdeburg Hauptbahnhof",
    region: "Sachsen-Anhalt",
    lat: 52.1306,
    lon: 11.6278,
    isDefault: false,
  },
  {
    name: "Halle (Saale) Hbf",
    displayName: "Halle (Saale) Hauptbahnhof",
    region: "Sachsen-Anhalt",
    lat: 51.4822,
    lon: 11.986,
    isDefault: false,
  },
  {
    name: "Potsdam Hbf",
    displayName: "Potsdam Hauptbahnhof",
    region: "Brandenburg",
    lat: 52.3906,
    lon: 13.0686,
    isDefault: false,
  },
  {
    name: "Würzburg Hbf",
    displayName: "Würzburg Hauptbahnhof",
    region: "Bayern",
    lat: 49.8019,
    lon: 9.9347,
    isDefault: false,
  },
  {
    name: "Bamberg",
    displayName: "Bamberg",
    region: "Bayern",
    lat: 49.8975,
    lon: 10.9019,
    isDefault: false,
  },
  {
    name: "Ingolstadt Hbf",
    displayName: "Ingolstadt Hauptbahnhof",
    region: "Bayern",
    lat: 48.744537,
    lon: 11.437335,
    isDefault: false,
  },
  {
    name: "KASSEL",
    displayName: "Kassel",
    region: "Hessen",
    lat: 51.3127,
    lon: 9.4474,
    isDefault: false,
  },
  {
    name: "Trier Hbf",
    displayName: "Trier Hauptbahnhof",
    region: "Rheinland-Pfalz",
    lat: 49.7586,
    lon: 6.6419,
    isDefault: false,
  },
  {
    name: "Saarbrücken Hbf",
    displayName: "Saarbrücken Hauptbahnhof",
    region: "Saarland",
    lat: 49.2405,
    lon: 6.9913,
    isDefault: false,
  },
  {
    name: "Bochum Hbf",
    displayName: "Bochum Hauptbahnhof",
    region: "Nordrhein-Westfalen",
    lat: 51.4785,
    lon: 7.2209,
    isDefault: false,
  },
  {
    name: "Konstanz",
    displayName: "Konstanz",
    region: "Baden-Württemberg",
    lat: 47.6608,
    lon: 9.1757,
    isDefault: false,
  },

  // Europäische Ziele mit Direktanbindung aus Deutschland
  {
    name: "Wien Hbf",
    displayName: "Wien Hauptbahnhof",
    region: "Europa",
    lat: 48.1851,
    lon: 16.3763,
    isDefault: false,
  },
  {
    name: "Prag Hbf",
    displayName: "Prag Hauptbahnhof",
    region: "Europa",
    lat: 50.083057,
    lon: 14.436038,
    isDefault: false,
  },
  {
    name: "Amsterdam Centraal",
    displayName: "Amsterdam Centraal",
    region: "Europa",
    lat: 52.3791,
    lon: 4.8997,
    isDefault: false,
  },
  {
    name: "Zürich HB",
    displayName: "Zürich Hauptbahnhof",
    region: "Europa",
    lat: 47.3779,
    lon: 8.5403,
    isDefault: false,
  },
  {
    name: "Bruxelles-Midi",
    displayName: "Brüssel Midi",
    region: "Europa",
    lat: 50.8364,
    lon: 4.3355,
    isDefault: false,
  },
  {
    name: "Strasbourg",
    displayName: "Strasbourg",
    region: "Europa",
    lat: 48.5851,
    lon: 7.7347,
    isDefault: false,
  },
  {
    name: "Paris Est",
    displayName: "Paris Est",
    region: "Europa",
    lat: 48.8769,
    lon: 2.3594,
    isDefault: false,
  },
  {
    name: "Warszawa Centralna",
    displayName: "Warschau Centralna",
    region: "Europa",
    lat: 52.2285,
    lon: 21.0034,
    isDefault: false,
  },
  {
    name: "Innsbruck Hbf",
    displayName: "Innsbruck Hauptbahnhof",
    region: "Europa",
    lat: 47.2631,
    lon: 11.4009,
    isDefault: false,
  },
  {
    name: "Salzburg Hbf",
    displayName: "Salzburg Hauptbahnhof",
    region: "Europa",
    lat: 47.8127,
    lon: 13.0456,
    isDefault: false,
  },
]

export function getDefaultStations(): ICEStation[] {
  return ICE_STATIONS.filter(station => station.isDefault)
}

export function getStationByName(name: string): ICEStation | undefined {
  return ICE_STATIONS.find(
    station => station.name.toLowerCase() === name.toLowerCase()
  )
}
